### ISSUE TITLE
Implement changeable primary UI color

### ISSUE THREAD

**Issue by jaohara** [jaohara/ui-component-library#8]
This would change the highlight color of the buttons, links, etc.

- This can be handled with CSS variables applied to a `:root` pseudoclass in a global stylesheet:

```css
:root {
  // among other variables:
  --primary-color: #007bff;
}

// ---
// In a component:
// ---

button {
  background-color: var(--primary-color);
}
```

By using this approach of defining CSS variables on the root pseudoclass, all other stylesheets will automatically have access to these variables without needing to import them like I'm doing with Sass.

More importantly, these variables can be modified at runtime. I should have a function somewhere in the library that does something like this:

```js
function changePrimaryColor(newColor) {
  document.documentElement.style.setProperty('--primary-color', newColor);
};
```

**I need to look more into where this function should live.**
